# Generated by Django 5.1.15 on 2026-04-16 03:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_alter_carrera_options_alter_generacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1', max_length=20, verbose_name='Versión')),
                ('num_parciales', models.PositiveSmallIntegerField(choices=[(1, '1 parcial'), (2, '2 parciales'), (3, '3 parciales')], default=2, verbose_name='Número de parciales')),
                ('permite_exencion', models.BooleanField(default=False, verbose_name='Permite exención')),
                ('peso_parciales', models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=5, verbose_name='Peso parciales')),
                ('peso_final', models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=5, verbose_name='Peso final')),
                ('umbral_exencion', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, verbose_name='Umbral de exención')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('materia_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esquemas_evaluacion', to='catalogos.materiaplan', verbose_name='Materia plan')),
            ],
            options={
                'verbose_name': 'Esquema de evaluación',
                'verbose_name_plural': 'Esquemas de evaluación',
                'ordering': ['-activo', 'materia_plan__plan_estudios__clave', 'materia_plan__materia__clave'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_codigo', models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Final')], max_length=10, verbose_name='Corte')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('es_examen', models.BooleanField(default=False, verbose_name='Es examen')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='evaluacion.esquemaevaluacion', verbose_name='Esquema')),
            ],
            options={
                'verbose_name': 'Componente de evaluación',
                'verbose_name_plural': 'Componentes de evaluación',
                'ordering': ['esquema', 'corte_codigo', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='esquemaevaluacion',
            constraint=models.UniqueConstraint(fields=('materia_plan', 'version'), name='uq_esquemaevaluacion_materiaplan_version'),
        ),
        migrations.AddConstraint(
            model_name='componenteevaluacion',
            constraint=models.UniqueConstraint(fields=('esquema', 'corte_codigo', 'orden'), name='uq_componenteevaluacion_esquema_corte_orden'),
        ),
    ]
