# Generated by Django 5.1.15 on 2026-04-23 20:58

from decimal import Decimal
from django.db import migrations, models


def convert_umbral_exencion_to_0_10(apps, schema_editor):
    EsquemaEvaluacion = apps.get_model("evaluacion", "EsquemaEvaluacion")

    for esquema in EsquemaEvaluacion.objects.all().only("id", "umbral_exencion"):
        umbral = esquema.umbral_exencion
        if umbral is None:
            continue
        if Decimal("10.00") < umbral <= Decimal("100.00"):
            esquema.umbral_exencion = (umbral / Decimal("10")).quantize(Decimal("0.01"))
            esquema.save(update_fields=["umbral_exencion"])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_internal_backend_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemaevaluacion',
            name='umbral_exencion',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Calificación mínima para exentar en escala de 0 a 10.', max_digits=5, verbose_name='Umbral de exención'),
        ),
        migrations.RunPython(
            convert_umbral_exencion_to_0_10,
            migrations.RunPython.noop,
        ),
    ]
