# Generated by Django 5.1.15 on 2026-04-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_alter_esquemaevaluacion_umbral_exencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemaevaluacion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este esquema puede usarse en actas y cálculos. Si se desactiva, queda solo para consulta histórica.', verbose_name='Disponible para evaluación'),
        ),
    ]
