# Generated by Django 5.1.15 on 2026-04-25 14:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_esquemaevaluacion_activo'),
        ('relaciones', '0003_adscripciongrupo_alter_inscripcionmateria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaCalificacionPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_codigo', models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Final')], editable=False, max_length=10, verbose_name='Corte académico')),
                ('valor', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), message='La calificación mínima es 0.0.'), django.core.validators.MaxValueValidator(Decimal('10.0'), message='La calificación máxima es 10.0.')], verbose_name='Valor capturado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('capturado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_calificacion_preliminar', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que captura')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_preliminares', to='evaluacion.componenteevaluacion', verbose_name='Componente de evaluación')),
                ('inscripcion_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_preliminares', to='relaciones.inscripcionmateria', verbose_name='Inscripción a asignatura')),
            ],
            options={
                'verbose_name': 'Captura preliminar de calificación',
                'verbose_name_plural': 'Capturas preliminares de calificaciones',
                'ordering': ['inscripcion_materia__discente__matricula', 'corte_codigo', 'componente__orden'],
                'constraints': [models.UniqueConstraint(fields=('inscripcion_materia', 'componente'), name='uq_capturacalificacionpreliminar_inscripcion_componente')],
            },
        ),
    ]
