# Generated by Django 5.1.15 on 2026-05-10 22:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_capturacalificacionpreliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemaevaluacion',
            name='umbral_exencion',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Calificación mínima para exentar en escala de 0 a 10.', max_digits=5, verbose_name='Umbral de exención'),
        ),
    ]
