# Generated by Django 5.1.15 on 2026-05-11 00:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_alter_esquemaevaluacion_umbral_exencion'),
        ('relaciones', '0003_adscripciongrupo_alter_inscripcionmateria_options_and_more'),
        ('usuarios', '0015_alter_asignacioncargo_cargo_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_codigo', models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Final')], max_length=10, verbose_name='Corte academico')),
                ('estado_acta', models.CharField(choices=[('BORRADOR_DOCENTE', 'Borrador docente'), ('PUBLICADO_DISCENTE', 'Publicado a discente'), ('REMITIDO_JEFATURA_CARRERA', 'Remitido a jefatura de carrera'), ('VALIDADO_JEFATURA_CARRERA', 'Validado por jefatura de carrera'), ('FORMALIZADO_JEFATURA_ACADEMICA', 'Formalizado por jefatura academica'), ('ARCHIVADO', 'Archivado')], default='BORRADOR_DOCENTE', max_length=40, verbose_name='Estado del acta')),
                ('esquema_version_snapshot', models.CharField(max_length=20, verbose_name='Version del esquema')),
                ('peso_parciales_snapshot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso parciales usado')),
                ('peso_final_snapshot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso final usado')),
                ('umbral_exencion_snapshot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Umbral de exencion usado')),
                ('publicada_en', models.DateTimeField(blank=True, null=True, verbose_name='Publicada en')),
                ('remitida_en', models.DateTimeField(blank=True, null=True, verbose_name='Remitida en')),
                ('formalizada_en', models.DateTimeField(blank=True, null=True, verbose_name='Formalizada en')),
                ('archivada_en', models.DateTimeField(blank=True, null=True, verbose_name='Archivada en')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('asignacion_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='relaciones.asignaciondocente', verbose_name='Asignacion docente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='evaluacion.esquemaevaluacion', verbose_name='Esquema de evaluacion usado')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_corte', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Resultado del corte')),
                ('resultado_corte_visible', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Resultado visible del corte')),
                ('promedio_parciales', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Promedio de parciales')),
                ('promedio_parciales_visible', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Promedio de parciales visible')),
                ('resultado_final_preliminar', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Resultado final preliminar')),
                ('resultado_final_preliminar_visible', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Resultado final preliminar visible')),
                ('resultado_preliminar', models.CharField(default='INCOMPLETO', max_length=20, verbose_name='Estado preliminar')),
                ('exencion_aplica', models.BooleanField(default=False, verbose_name='Exencion aplica')),
                ('completo', models.BooleanField(default=False, verbose_name='Completo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='evaluacion.acta', verbose_name='Acta')),
                ('inscripcion_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_acta', to='relaciones.inscripcionmateria', verbose_name='Inscripcion a asignatura')),
            ],
            options={
                'verbose_name': 'Detalle de acta',
                'verbose_name_plural': 'Detalles de acta',
                'ordering': ['inscripcion_materia__discente__matricula'],
            },
        ),
        migrations.CreateModel(
            name='ConformidadDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conformidad', models.CharField(choices=[('ACUSE', 'Acuse de recibo'), ('CONFORME', 'Conforme'), ('INCONFORME', 'Inconforme')], default='ACUSE', max_length=20, verbose_name='Conformidad')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('invalidado_en', models.DateTimeField(blank=True, null=True, verbose_name='Invalidado en')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conformidades_acta', to='relaciones.discente', verbose_name='Discente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conformidades_acta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformidades', to='evaluacion.detalleacta', verbose_name='Detalle de acta')),
            ],
            options={
                'verbose_name': 'Conformidad de discente',
                'verbose_name_plural': 'Conformidades de discentes',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_nombre_snapshot', models.CharField(max_length=120, verbose_name='Nombre del componente usado')),
                ('componente_porcentaje_snapshot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje del componente usado')),
                ('componente_es_examen_snapshot', models.BooleanField(default=False, verbose_name='Era examen final')),
                ('valor_capturado', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Valor capturado')),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Valor ponderado')),
                ('sustituido_por_exencion', models.BooleanField(default=False, verbose_name='Sustituido por exencion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_acta', to='evaluacion.componenteevaluacion', verbose_name='Componente original')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_componentes', to='evaluacion.detalleacta', verbose_name='Detalle de acta')),
            ],
            options={
                'verbose_name': 'Calificacion por componente de acta',
                'verbose_name_plural': 'Calificaciones por componente de acta',
                'ordering': ['componente__orden', 'componente_id'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_validacion', models.CharField(choices=[('DOCENTE', 'Docente'), ('JEFATURA_CARRERA', 'Jefatura de carrera'), ('JEFATURA_ACADEMICA', 'Jefatura academica'), ('SISTEMA', 'Sistema')], max_length=30, verbose_name='Etapa de validacion')),
                ('accion', models.CharField(choices=[('PUBLICA', 'Publica'), ('REMITE', 'Remite'), ('VALIDA', 'Valida'), ('FORMALIZA', 'Formaliza'), ('ARCHIVA', 'Archiva')], max_length=20, verbose_name='Accion')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP origen')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='evaluacion.acta', verbose_name='Acta')),
                ('asignacion_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_acta', to='usuarios.asignacioncargo', verbose_name='Asignacion de cargo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_acta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Validacion de acta',
                'verbose_name_plural': 'Validaciones de acta',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='acta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_acta', 'ARCHIVADO'), _negated=True), fields=('asignacion_docente', 'corte_codigo'), name='uq_acta_activa_asignacion_corte'),
        ),
        migrations.AddConstraint(
            model_name='detalleacta',
            constraint=models.UniqueConstraint(fields=('acta', 'inscripcion_materia'), name='uq_detalleacta_acta_inscripcion'),
        ),
        migrations.AddConstraint(
            model_name='conformidaddiscente',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('detalle', 'discente'), name='uq_conformidaddiscente_vigente_detalle_discente'),
        ),
        migrations.AddConstraint(
            model_name='calificacioncomponente',
            constraint=models.UniqueConstraint(fields=('detalle', 'componente'), name='uq_calificacioncomponente_detalle_componente'),
        ),
    ]
