# Generated by Django 5.1.15 on 2026-05-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_acta_detalleacta_conformidaddiscente_and_more'),
        ('relaciones', '0003_adscripciongrupo_alter_inscripcionmateria_options_and_more'),
        ('usuarios', '0015_alter_asignacioncargo_cargo_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacioncomponente',
            options={'ordering': ['componente__orden', 'componente_id'], 'verbose_name': 'Calificación por componente de acta', 'verbose_name_plural': 'Calificaciones por componente de acta'},
        ),
        migrations.AlterModelOptions(
            name='validacionacta',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Validación de acta', 'verbose_name_plural': 'Validaciones de acta'},
        ),
        migrations.AlterField(
            model_name='acta',
            name='asignacion_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='relaciones.asignaciondocente', verbose_name='Asignación docente'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='corte_codigo',
            field=models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Evaluación final')], max_length=10, verbose_name='Corte académico'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='esquema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='evaluacion.esquemaevaluacion', verbose_name='Esquema de evaluación usado'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='esquema_version_snapshot',
            field=models.CharField(max_length=20, verbose_name='Versión del esquema'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='estado_acta',
            field=models.CharField(choices=[('BORRADOR_DOCENTE', 'Borrador docente'), ('PUBLICADO_DISCENTE', 'Publicado a discentes'), ('REMITIDO_JEFATURA_CARRERA', 'Remitido a jefatura de carrera'), ('VALIDADO_JEFATURA_CARRERA', 'Validado por jefatura de carrera'), ('FORMALIZADO_JEFATURA_ACADEMICA', 'Formalizado por jefatura académica'), ('ARCHIVADO', 'Archivado')], default='BORRADOR_DOCENTE', max_length=40, verbose_name='Estado del acta'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='umbral_exencion_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Umbral de exención usado'),
        ),
        migrations.AlterField(
            model_name='calificacioncomponente',
            name='sustituido_por_exencion',
            field=models.BooleanField(default=False, verbose_name='Sustituido por exención'),
        ),
        migrations.AlterField(
            model_name='capturacalificacionpreliminar',
            name='corte_codigo',
            field=models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Evaluación final')], editable=False, max_length=10, verbose_name='Corte académico'),
        ),
        migrations.AlterField(
            model_name='componenteevaluacion',
            name='corte_codigo',
            field=models.CharField(choices=[('P1', 'Parcial 1'), ('P2', 'Parcial 2'), ('P3', 'Parcial 3'), ('FINAL', 'Evaluación final')], max_length=10, verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='detalleacta',
            name='exencion_aplica',
            field=models.BooleanField(default=False, verbose_name='Exención aplicable'),
        ),
        migrations.AlterField(
            model_name='detalleacta',
            name='inscripcion_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_acta', to='relaciones.inscripcionmateria', verbose_name='Inscripción a asignatura'),
        ),
        migrations.AlterField(
            model_name='validacionacta',
            name='accion',
            field=models.CharField(choices=[('PUBLICA', 'Publica'), ('REMITE', 'Remite'), ('VALIDA', 'Valida'), ('FORMALIZA', 'Formaliza'), ('ARCHIVA', 'Archiva')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='validacionacta',
            name='asignacion_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_acta', to='usuarios.asignacioncargo', verbose_name='Asignación de cargo'),
        ),
        migrations.AlterField(
            model_name='validacionacta',
            name='etapa_validacion',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('JEFATURA_CARRERA', 'Jefatura de carrera'), ('JEFATURA_ACADEMICA', 'Jefatura académica'), ('SISTEMA', 'Sistema')], max_length=30, verbose_name='Etapa de validación'),
        ),
    ]
