# Generated by Django 5.1.15 on 2026-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_alter_calificacioncomponente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='probables_causas_reprobacion',
            field=models.TextField(blank=True, verbose_name='Probables causas de reprobación'),
        ),
        migrations.AddField(
            model_name='acta',
            name='sugerencias_academicas',
            field=models.TextField(blank=True, verbose_name='Sugerencias académicas'),
        ),
    ]
