# Generated by Django 5.1.15 on 2026-05-12 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0017_programaasignatura_ubicacion_excepcional_and_more'),
        ('relaciones', '0003_adscripciongrupo_alter_inscripcionmateria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoResultadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Resultado académico',
                'verbose_name_plural': 'Resultados académicos',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoSituacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Situación académica',
                'verbose_name_plural': 'Situaciones académicas',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='EventoSituacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_situacion', to='relaciones.discente', verbose_name='Discente')),
                ('inscripcion_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_situacion_academica', to='relaciones.inscripcionmateria', verbose_name='Inscripción relacionada')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_situacion_academica', to='catalogos.periodoescolar', verbose_name='Periodo académico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_situacion_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='trayectoria.catalogosituacionacademica', verbose_name='Situación')),
            ],
            options={
                'verbose_name': 'Evento de situación académica',
                'verbose_name_plural': 'Eventos de situación académica',
                'ordering': ['discente__matricula', '-fecha_inicio', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Extraordinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de aplicación')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))], verbose_name='Calificación')),
                ('aprobado', models.BooleanField(default=False, editable=False, verbose_name='Aprobado')),
                ('codigo_resultado_oficial', models.CharField(blank=True, max_length=40, verbose_name='Código de resultado oficial')),
                ('codigo_marca', models.CharField(blank=True, max_length=20, verbose_name='Código de marca')),
                ('calificacion_ordinaria', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Calificación ordinaria preservada')),
                ('codigo_resultado_ordinario', models.CharField(blank=True, editable=False, max_length=40, verbose_name='Resultado ordinario preservado')),
                ('codigo_marca_ordinaria', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Marca ordinaria preservada')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('inscripcion_materia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extraordinario', to='relaciones.inscripcionmateria', verbose_name='Inscripción a asignatura')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraordinarios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Extraordinario',
                'verbose_name_plural': 'Extraordinarios',
                'ordering': ['-fecha_aplicacion', 'inscripcion_materia__discente__matricula'],
            },
        ),
    ]
