# Generated by Django 5.1.15 on 2026-04-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['clave', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creditos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_totales', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['clave', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-vigente_desde', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='catalogos.carrera')),
            ],
            options={
                'ordering': ['carrera__clave', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField(default=1)),
                ('orden_malla', models.PositiveIntegerField(default=1)),
                ('obligatoria', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='catalogos.materia')),
                ('plan_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_plan', to='catalogos.planestudios')),
            ],
            options={
                'ordering': ['plan_estudios__clave', 'orden_malla', 'materia__clave'],
            },
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('anio_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plan_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generaciones', to='catalogos.planestudios')),
            ],
            options={
                'ordering': ['-anio_inicio', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('nocturno', 'Nocturno')], default='matutino', max_length=20)),
                ('cupo_maximo', models.PositiveIntegerField(default=40)),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_academicos', to='catalogos.generacion')),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_academicos', to='catalogos.periodoescolar')),
            ],
            options={
                'ordering': ['periodo_escolar__clave', 'clave'],
                'constraints': [models.UniqueConstraint(fields=('generacion', 'periodo_escolar', 'clave'), name='uq_grupo_generacion_periodo_clave')],
            },
        ),
        migrations.AddConstraint(
            model_name='planestudios',
            constraint=models.UniqueConstraint(fields=('carrera', 'clave'), name='uq_planestudios_carrera_clave'),
        ),
        migrations.AddConstraint(
            model_name='materiaplan',
            constraint=models.UniqueConstraint(fields=('plan_estudios', 'materia'), name='uq_materiaplan_plan_materia'),
        ),
        migrations.AddConstraint(
            model_name='generacion',
            constraint=models.UniqueConstraint(fields=('plan_estudios', 'clave'), name='uq_generacion_plan_clave'),
        ),
    ]
