# Generated by Django 5.1.15 on 2026-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(fields=('clave',), name='uq_carrera_clave'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('clave',), name='uq_materia_clave'),
        ),
        migrations.AddConstraint(
            model_name='periodoescolar',
            constraint=models.UniqueConstraint(fields=('clave',), name='uq_periodoescolar_clave'),
        ),
    ]
