# Generated by Django 5.1.15 on 2026-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_carrera_uq_carrera_clave_materia_uq_materia_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoescolar',
            name='anio_escolar',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='periodoescolar',
            name='semestre_operativo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='periodoescolar',
            old_name='vigente_desde',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='periodoescolar',
            old_name='vigente_hasta',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='periodoescolar',
            name='nombre',
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'ordering': ['-anio_escolar', '-semestre_operativo', 'clave']},
        ),
        migrations.RemoveConstraint(
            model_name='grupoacademico',
            name='uq_grupo_generacion_periodo_clave',
        ),
        migrations.RenameField(
            model_name='grupoacademico',
            old_name='clave',
            new_name='clave_grupo',
        ),
        migrations.RenameField(
            model_name='grupoacademico',
            old_name='periodo_escolar',
            new_name='periodo',
        ),
        migrations.AddField(
            model_name='grupoacademico',
            name='semestre_numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='grupoacademico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='grupoacademico',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='grupoacademico',
            name='vigente_desde',
        ),
        migrations.RemoveField(
            model_name='grupoacademico',
            name='vigente_hasta',
        ),
        migrations.AlterModelOptions(
            name='grupoacademico',
            options={'ordering': ['periodo__anio_escolar', 'periodo__semestre_operativo', 'clave_grupo']},
        ),
        migrations.AddConstraint(
            model_name='grupoacademico',
            constraint=models.UniqueConstraint(fields=('generacion', 'periodo', 'clave_grupo'), name='uq_grupo_generacion_periodo_clave'),
        ),
        migrations.RenameField(
            model_name='materiaplan',
            old_name='semestre',
            new_name='semestre_numero',
        ),
        migrations.AddField(
            model_name='materiaplan',
            name='anio_escolar_numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='materiaplan',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='materiaplan',
            name='orden_malla',
        ),
        migrations.RemoveField(
            model_name='materiaplan',
            name='vigente_desde',
        ),
        migrations.RemoveField(
            model_name='materiaplan',
            name='vigente_hasta',
        ),
        migrations.AlterModelOptions(
            name='materiaplan',
            options={'ordering': ['plan_estudios__clave', 'anio_escolar_numero', 'semestre_numero', 'materia__clave']},
        ),
    ]
