# Generated by Django 5.1.15 on 2026-04-16 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_correccion_bloque2_baseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['clave', 'nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='generacion',
            options={'ordering': ['-anio_inicio', 'clave'], 'verbose_name': 'Generación', 'verbose_name_plural': 'Generaciones'},
        ),
        migrations.AlterModelOptions(
            name='grupoacademico',
            options={'ordering': ['periodo__anio_escolar', 'periodo__semestre_operativo', 'clave_grupo'], 'verbose_name': 'Grupo académico', 'verbose_name_plural': 'Grupos académicos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['clave', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='materiaplan',
            options={'ordering': ['plan_estudios__clave', 'anio_escolar_numero', 'semestre_numero', 'materia__clave'], 'verbose_name': 'Plan de materia', 'verbose_name_plural': 'Planes de materias'},
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'ordering': ['-anio_escolar', '-semestre_operativo', 'clave'], 'verbose_name': 'Periodo escolar', 'verbose_name_plural': 'Periodo escolar'},
        ),
        migrations.AlterModelOptions(
            name='planestudios',
            options={'ordering': ['carrera__clave', 'clave'], 'verbose_name': 'Plan de estudio', 'verbose_name_plural': 'Planes de estudio'},
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='clave_grupo',
            field=models.CharField(max_length=30, verbose_name='Clave de grupo'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo máximo'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_academicos', to='catalogos.generacion', verbose_name='Generación'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_academicos', to='catalogos.periodoescolar', verbose_name='Periodo escolar'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='semestre_numero',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Semestre número'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='anio_escolar_numero',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Año escolar número'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='catalogos.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='obligatoria',
            field=models.BooleanField(default=True, verbose_name='Obligatoria'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='plan_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_plan', to='catalogos.planestudios', verbose_name='Plan de estudio'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='semestre_numero',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Semestre número'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='anio_escolar',
            field=models.CharField(blank=True, choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035')], default='', max_length=20, verbose_name='Año escolar'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='clave',
            field=models.CharField(max_length=30, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='semestre_operativo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], null=True, verbose_name='Semestre operativo'),
        ),
    ]
