# Generated by Django 5.1.15 on 2026-04-22 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_carrera_options_alter_generacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='generacion',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='clave_grupo',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')], verbose_name='Clave de grupo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')], verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='planestudios',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')]),
        ),
    ]
