# Generated by Django 5.1.15 on 2026-04-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_alter_carrera_clave_alter_generacion_clave_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generacion",
            options={
                "ordering": ["-anio_inicio", "clave"],
                "verbose_name": "Antigüedad",
                "verbose_name_plural": "Antigüedades",
            },
        ),
        migrations.AlterField(
            model_name="grupoacademico",
            name="generacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos_academicos",
                to="catalogos.generacion",
                verbose_name="Antigüedad",
            ),
        ),
    ]
