# Generated by Django 5.1.15 on 2026-04-22 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_generacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='generacion',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='planestudios',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
