# Generated by Django 5.1.15 on 2026-04-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_alter_carrera_vigente_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacion',
            name='anio_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de fin'),
        ),
        migrations.AlterField(
            model_name='generacion',
            name='anio_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de inicio'),
        ),
    ]
