# Generated by Django 5.1.15 on 2026-04-23 02:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_generacion_anio_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materia',
            name='horas_totales',
            field=models.PositiveIntegerField(help_text='Los creditos se calculan automaticamente a partir de las horas totales.', validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0.')]),
        ),
    ]
