# Generated by Django 5.1.15 on 2026-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_materia_creditos_alter_materia_horas_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
