# Generated by Django 5.1.15 on 2026-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_materia_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoescolar',
            name='anio_escolar',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035')], max_length=20, verbose_name='Año escolar'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_fin',
            field=models.DateField(null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='semestre_operativo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], null=True, verbose_name='Periodo académico'),
        ),
    ]
