# Generated by Django 5.1.15 on 2026-04-23 03:12

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_alter_periodoescolar_anio_escolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoescolar',
            name='anio_escolar',
            field=models.CharField(choices=catalogos.models.build_anio_escolar_choices, max_length=20, verbose_name='Año escolar'),
        ),
    ]
