# Generated by Django 5.1.15 on 2026-04-23 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_alter_periodoescolar_anio_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoacademico',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0.')], verbose_name='Cupo máximo'),
        ),
        migrations.AlterField(
            model_name='grupoacademico',
            name='semestre_numero',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, verbose_name='Semestre'),
        ),
    ]
