# Generated by Django 5.1.15 on 2026-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_grupoacademico_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaplan',
            options={'ordering': ['plan_estudios__clave', 'anio_escolar_numero', 'semestre_numero', 'materia__clave'], 'verbose_name': 'Programa de asignatura', 'verbose_name_plural': 'Programas de asignatura'},
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='anio_escolar_numero',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Año de formación'),
        ),
        migrations.AlterField(
            model_name='materiaplan',
            name='semestre_numero',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, verbose_name='Semestre'),
        ),
    ]
