# Generated by Django 5.1.15 on 2026-04-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_restore_decimal_creditos_and_recalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaasignatura',
            name='ubicacion_excepcional',
            field=models.BooleanField(default=False, help_text='Activa esta opción solo para materias que pueden cursarse en semestres distintos según la antigüedad. Si está desactivada, se usa el semestre normal.', verbose_name='Usar ubicación excepcional por antigüedad'),
        ),
        migrations.CreateModel(
            name='ProgramaAsignaturaUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_numero', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Semestre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('antiguedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_programas_asignatura', to='catalogos.antiguedad', verbose_name='Antigüedad')),
                ('programa_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_excepcionales', to='catalogos.programaasignatura', verbose_name='Programa de asignatura')),
            ],
            options={
                'verbose_name': 'Ubicación excepcional de programa',
                'verbose_name_plural': 'Ubicaciones excepcionales de programas',
                'db_table': 'catalogos_programa_asignatura_ubicacion',
                'ordering': ['programa_asignatura__plan_estudios__clave', 'programa_asignatura__materia__clave', 'antiguedad__clave', 'semestre_numero'],
                'constraints': [models.UniqueConstraint(fields=('programa_asignatura', 'antiguedad', 'semestre_numero'), name='uq_programa_ubicacion_antiguedad_semestre')],
            },
        ),
    ]
