# Generated by Django 5.1.15 on 2026-05-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_programaasignatura_ubicacion_excepcional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoescolar',
            name='estado',
            field=models.CharField(choices=[('planificado', 'Planificado'), ('activo', 'Abierto'), ('cerrado', 'Cerrado'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado'),
        ),
    ]
