# Generated by Django 5.1.15 on 2026-04-23 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0016_restore_decimal_creditos_and_recalculate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('grupo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docentes', to='catalogos.grupoacademico', verbose_name='Grupo académico')),
                ('programa_asignatura', models.ForeignKey(db_column='materia_plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docentes', to='catalogos.programaasignatura', verbose_name='Programa de asignatura')),
                ('usuario_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docentes', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignación docente',
                'verbose_name_plural': 'Asignaciones docentes',
                'ordering': ['-activo', 'grupo_academico__periodo__anio_escolar', 'grupo_academico__clave_grupo', 'programa_asignatura__materia__clave'],
            },
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('situacion_actual', models.CharField(choices=[('regular', 'Regular'), ('baja_temporal', 'Baja temporal'), ('baja_definitiva', 'Baja definitiva'), ('egresado', 'Egresado')], default='regular', max_length=30, verbose_name='Situación actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('antiguedad', models.ForeignKey(db_column='generacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='discentes', to='catalogos.antiguedad', verbose_name='Antigüedad')),
                ('plan_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discentes', to='catalogos.planestudios', verbose_name='Plan de estudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_discente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Discente',
                'verbose_name_plural': 'Discentes',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inscripcion', models.CharField(choices=[('inscrita', 'Inscrita'), ('baja', 'Baja'), ('cerrada', 'Cerrada')], default='inscrita', max_length=20, verbose_name='Estado de inscripción')),
                ('intento_numero', models.PositiveSmallIntegerField(default=1, verbose_name='Intento')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación final')),
                ('codigo_resultado_oficial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de resultado oficial')),
                ('codigo_marca', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de marca')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado en')),
                ('asignacion_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_materia', to='relaciones.asignaciondocente', verbose_name='Asignación docente')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_materia', to='relaciones.discente', verbose_name='Discente')),
            ],
            options={
                'verbose_name': 'Inscripción a materia',
                'verbose_name_plural': 'Inscripciones a materia',
                'ordering': ['discente__matricula', 'asignacion_docente__grupo_academico__periodo__anio_escolar', 'asignacion_docente__programa_asignatura__materia__clave', 'intento_numero'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('cambio_grupo', 'Cambio de grupo'), ('alta_extemporanea', 'Alta extemporánea'), ('baja_extemporanea', 'Baja extemporánea')], max_length=30, verbose_name='Tipo de movimiento')),
                ('fecha_movimiento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de movimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_academicos', to='relaciones.discente', verbose_name='Discente')),
                ('grupo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='catalogos.grupoacademico', verbose_name='Grupo destino')),
                ('grupo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='catalogos.grupoacademico', verbose_name='Grupo origen')),
                ('periodo', models.ForeignKey(db_column='periodo_escolar_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_academicos', to='catalogos.periodoescolar', verbose_name='Periodo escolar')),
            ],
            options={
                'verbose_name': 'Movimiento académico',
                'verbose_name_plural': 'Movimientos académicos',
                'ordering': ['-fecha_movimiento', 'discente__matricula'],
            },
        ),
        migrations.AddConstraint(
            model_name='discente',
            constraint=models.UniqueConstraint(fields=('usuario',), name='uq_discente_usuario'),
        ),
    ]
