# Generated by Django 5.1.15 on 2026-04-23 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_restore_decimal_creditos_and_recalculate'),
        ('relaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('grupo_academico', 'programa_asignatura'), name='uq_asignaciondocente_activa_grupo_programa'),
        ),
    ]
