# Generated by Django 5.1.15 on 2026-04-24 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_restore_decimal_creditos_and_recalculate'),
        ('relaciones', '0002_asignaciondocente_uq_asignaciondocente_activa_grupo_programa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdscripcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Adscripción a grupo',
                'verbose_name_plural': 'Adscripciones a grupo',
                'ordering': ['-activo', 'grupo_academico__periodo__anio_escolar', 'grupo_academico__clave_grupo', 'discente__matricula'],
            },
        ),
        migrations.AlterModelOptions(
            name='inscripcionmateria',
            options={'ordering': ['discente__matricula', 'asignacion_docente__grupo_academico__periodo__anio_escolar', 'asignacion_docente__programa_asignatura__materia__clave', 'intento_numero'], 'verbose_name': 'Inscripción a asignatura', 'verbose_name_plural': 'Inscripciones a asignatura'},
        ),
        migrations.RemoveConstraint(
            model_name='discente',
            name='uq_discente_usuario',
        ),
        migrations.AddConstraint(
            model_name='discente',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario',), name='uq_discente_activo_usuario'),
        ),
        migrations.AddConstraint(
            model_name='inscripcionmateria',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_inscripcion', 'inscrita')), fields=('discente', 'asignacion_docente'), name='uq_inscripcionmateria_activa_discente_asignacion'),
        ),
        migrations.AddField(
            model_name='adscripciongrupo',
            name='discente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adscripciones_grupo', to='relaciones.discente', verbose_name='Discente'),
        ),
        migrations.AddField(
            model_name='adscripciongrupo',
            name='grupo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adscripciones_discente', to='catalogos.grupoacademico', verbose_name='Grupo académico'),
        ),
        migrations.AddConstraint(
            model_name='adscripciongrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('discente', 'grupo_academico'), name='uq_adscripciongrupo_activa_discente_grupo'),
        ),
    ]
