# Generated by Django 5.1.15 on 2026-05-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ACTA_EVALUACION_PARCIAL', 'Acta de evaluación parcial'), ('ACTA_EVALUACION_FINAL', 'Acta de evaluación final'), ('ACTA_CALIFICACION_FINAL', 'Acta de calificación final'), ('KARDEX_OFICIAL', 'Kárdex oficial'), ('HISTORIAL_ACADEMICO', 'Historial académico'), ('REPORTE_ACTAS_ESTADO', 'Reporte de actas por estado'), ('REPORTE_ACTAS_PENDIENTES', 'Reporte de actas pendientes'), ('REPORTE_INCONFORMIDADES', 'Reporte de inconformidades'), ('REPORTE_DESEMPENO', 'Reporte de desempeño'), ('REPORTE_SITUACION_ACADEMICA', 'Reporte de situación académica'), ('REPORTE_VALIDACIONES_ACTA', 'Reporte de validaciones de acta'), ('REPORTE_EXPORTACIONES', 'Reporte de exportaciones'), ('REPORTE_MOVIMIENTOS_ACADEMICOS', 'Reporte de movimientos académicos'), ('AUDITORIA_EVENTOS', 'Auditoría de eventos'), ('OTRO', 'Otro')], max_length=60, verbose_name='Tipo de documento')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel XLSX'), ('CSV', 'CSV')], max_length=10, verbose_name='Formato')),
                ('nombre_documento', models.CharField(max_length=180, verbose_name='Nombre del documento')),
                ('nombre_archivo', models.CharField(max_length=220, verbose_name='Nombre de archivo')),
                ('objeto_tipo', models.CharField(blank=True, max_length=120, verbose_name='Tipo de objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=80, verbose_name='ID de objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=240, verbose_name='Representación del objeto')),
                ('filtros_json', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('parametros_json', models.JSONField(blank=True, default=dict, verbose_name='Parámetros')),
                ('rol_contexto', models.CharField(blank=True, max_length=80, verbose_name='Rol de contexto')),
                ('cargo_contexto', models.CharField(blank=True, max_length=80, verbose_name='Cargo de contexto')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User agent')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('GENERADA', 'Generada'), ('FALLIDA', 'Fallida'), ('DESCARGADA', 'Descargada')], default='SOLICITADA', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('tamano_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Tamaño en bytes')),
                ('hash_archivo', models.CharField(blank=True, max_length=128, verbose_name='Hash del archivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('finalizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_exportacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de exportación',
                'verbose_name_plural': 'Registros de exportación',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', '-creado_en'], name='idx_export_usuario_fecha'), models.Index(fields=['tipo_documento', 'estado'], name='idx_export_tipo_estado'), models.Index(fields=['formato', '-creado_en'], name='idx_export_formato_fecha')],
            },
        ),
    ]
