# Generated by Django 5.1.15 on 2026-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroexportacion',
            name='tipo_documento',
            field=models.CharField(choices=[('ACTA_EVALUACION_PARCIAL', 'Acta de evaluación parcial'), ('ACTA_EVALUACION_FINAL', 'Acta de evaluación final'), ('ACTA_CALIFICACION_FINAL', 'Acta de calificación final'), ('KARDEX_OFICIAL', 'Kárdex oficial'), ('HISTORIAL_ACADEMICO', 'Historial académico'), ('REPORTE_ACTAS_ESTADO', 'Reporte de actas por estado'), ('REPORTE_ACTAS_PENDIENTES', 'Reporte de actas pendientes'), ('REPORTE_INCONFORMIDADES', 'Reporte de inconformidades'), ('REPORTE_ACTAS_SIN_CONFORMIDAD', 'Reporte de actas sin conformidad'), ('REPORTE_ACTAS_FORMALIZADAS', 'Reporte de actas formalizadas'), ('REPORTE_DESEMPENO', 'Reporte de desempeño'), ('REPORTE_SITUACION_ACADEMICA', 'Reporte de situación académica'), ('REPORTE_VALIDACIONES_ACTA', 'Reporte de validaciones de acta'), ('REPORTE_EXPORTACIONES', 'Reporte de exportaciones'), ('REPORTE_MOVIMIENTOS_ACADEMICOS', 'Reporte de movimientos académicos'), ('AUDITORIA_EVENTOS', 'Auditoría de eventos'), ('OTRO', 'Otro')], max_length=60, verbose_name='Tipo de documento'),
        ),
    ]
