# Generated by Django 5.1.15 on 2026-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_registroexportacion_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroexportacion',
            name='tipo_documento',
            field=models.CharField(choices=[('ACTA_EVALUACION_PARCIAL', 'Acta de evaluación parcial'), ('ACTA_EVALUACION_FINAL', 'Acta de evaluación final'), ('ACTA_CALIFICACION_FINAL', 'Acta de calificación final'), ('KARDEX_OFICIAL', 'Kárdex oficial'), ('HISTORIAL_ACADEMICO', 'Historial académico'), ('REPORTE_ACTAS_ESTADO', 'Reporte de actas por estado'), ('REPORTE_ACTAS_PENDIENTES', 'Reporte de actas pendientes'), ('REPORTE_INCONFORMIDADES', 'Reporte de inconformidades'), ('REPORTE_ACTAS_SIN_CONFORMIDAD', 'Reporte de actas sin conformidad'), ('REPORTE_ACTAS_FORMALIZADAS', 'Reporte de actas formalizadas'), ('REPORTE_DESEMPENO', 'Reporte de desempeño'), ('REPORTE_APROBADOS_REPROBADOS', 'Reporte de aprobados y reprobados'), ('REPORTE_PROMEDIOS_ACADEMICOS', 'Reporte de promedios académicos'), ('REPORTE_DISTRIBUCION_CALIFICACIONES', 'Reporte de distribución de calificaciones'), ('REPORTE_EXENTOS', 'Reporte de exentos'), ('REPORTE_DESEMPENO_DOCENTE', 'Reporte de desempeño por docente'), ('REPORTE_DESEMPENO_COHORTE', 'Reporte de desempeño por cohorte'), ('REPORTE_REPROBADOS_NOMINAL', 'Reporte nominal de reprobados'), ('CUADRO_APROVECHAMIENTO', 'Cuadro de aprovechamiento'), ('REPORTE_SITUACION_ACADEMICA', 'Reporte de situación académica'), ('REPORTE_EXTRAORDINARIOS', 'Reporte de extraordinarios'), ('REPORTE_BAJAS_TEMPORALES', 'Reporte de bajas temporales'), ('REPORTE_BAJAS_DEFINITIVAS', 'Reporte de bajas definitivas'), ('REPORTE_REINGRESOS', 'Reporte de reingresos'), ('REPORTE_EGRESADOS_EGRESABLES', 'Reporte de egresados y egresables'), ('REPORTE_SITUACION_ACADEMICA_AGREGADO', 'Reporte agregado de situación académica'), ('REPORTE_VALIDACIONES_ACTA', 'Reporte de validaciones de acta'), ('REPORTE_EXPORTACIONES', 'Reporte de exportaciones'), ('REPORTE_MOVIMIENTOS_ACADEMICOS', 'Reporte de movimientos académicos'), ('REPORTE_CAMBIOS_GRUPO', 'Reporte de cambios de grupo'), ('REPORTE_HISTORIAL_ACADEMICO_INTERNO', 'Reporte de historial académico interno'), ('AUDITORIA_EVENTOS', 'Auditoría de eventos'), ('OTRO', 'Otro')], max_length=60, verbose_name='Tipo de documento'),
        ),
    ]
