# Generated by Django 5.1.15 on 2026-05-12 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0018_alter_periodoescolar_estado'),
        ('relaciones', '0003_adscripciongrupo_alter_inscripcionmateria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAperturaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True, verbose_name='Ejecutado en')),
                ('estado', models.CharField(choices=[('EJECUTADO', 'Ejecutado'), ('BLOQUEADO', 'Bloqueado')], max_length=20, verbose_name='Estado')),
                ('resumen_json', models.JSONField(blank=True, default=dict, verbose_name='Resumen')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ejecutado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_apertura_periodo', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('periodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_apertura_destino', to='catalogos.periodoescolar', verbose_name='Periodo destino')),
                ('periodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_apertura_origen', to='catalogos.periodoescolar', verbose_name='Periodo origen')),
            ],
            options={
                'verbose_name': 'Proceso de apertura de periodo',
                'verbose_name_plural': 'Procesos de apertura de periodo',
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoCierrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('CERRADO', 'Cerrado')], max_length=20, verbose_name='Estado')),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True, verbose_name='Ejecutado en')),
                ('resumen_json', models.JSONField(blank=True, default=dict, verbose_name='Resumen')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ejecutado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_cierre_periodo', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_cierre', to='catalogos.periodoescolar', verbose_name='Periodo académico')),
            ],
            options={
                'verbose_name': 'Proceso de cierre de periodo',
                'verbose_name_plural': 'Procesos de cierre de periodo',
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCierrePeriodoDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('PROMOVIBLE', 'Promovible'), ('EXTRAORDINARIO_PENDIENTE', 'Extraordinario pendiente'), ('BAJA_TEMPORAL', 'Baja temporal'), ('BAJA_DEFINITIVA', 'Baja definitiva'), ('EGRESABLE', 'Egresable'), ('NO_PROMOVIBLE', 'No promovible')], max_length=40, verbose_name='Clasificación')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('promovible', models.BooleanField(default=False, verbose_name='Promovible')),
                ('requiere_extraordinario', models.BooleanField(default=False, verbose_name='Requiere extraordinario')),
                ('situacion_detectada', models.CharField(blank=True, max_length=60, verbose_name='Situación detectada')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cierre_periodo', to='relaciones.discente', verbose_name='Discente')),
                ('grupo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cierre_origen', to='catalogos.grupoacademico', verbose_name='Grupo origen')),
                ('proceso_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_discente', to='actas.procesocierreperiodo', verbose_name='Proceso de cierre')),
            ],
            options={
                'verbose_name': 'Detalle de cierre por discente',
                'verbose_name_plural': 'Detalles de cierre por discente',
                'ordering': ['grupo_origen__clave_grupo', 'discente__matricula'],
                'constraints': [models.UniqueConstraint(fields=('proceso_cierre', 'discente'), name='uq_detalle_cierre_proceso_discente')],
            },
        ),
    ]
