# Generated by Django 5.1.15 on 2026-04-16 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='AsignacionCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_codigo', models.CharField(max_length=50)),
                ('tipo_designacion', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente'), ('accidental', 'Accidental')], max_length=20)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activo', '-vigente_desde', 'cargo_codigo'],
            },
        ),
    ]
