# Generated by Django 5.1.15 on 2026-04-22 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_seed_role_discente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncargo',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
