# Generated by Django 5.1.15 on 2026-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_asignacioncargo_vigente_desde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último acceso'),
        ),
    ]
