# Generated by Django 5.1.15 on 2026-04-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_date_joined_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncargo',
            name='cargo_codigo',
            field=models.CharField(choices=[('JEFE_CARRERA', 'Jefe de carrera'), ('JEFE_ACADEMICO', 'Jefe académico'), ('DOCENTE', 'Docente'), ('COORDINADOR', 'Coordinador')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='tipo_designacion',
            field=models.CharField(choices=[('titular', 'Titular'), ('accidental', 'Accidental')], max_length=20),
        ),
    ]
