# Generated by Django 5.1.15 on 2026-04-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_asignacioncargo_cargo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncargo',
            name='cargo_codigo',
            field=models.CharField(choices=[('JEFE_CARRERA_ICIS', 'Jefe de carrera de ICIS'), ('JEFE_CARRERA_ICES', 'Jefe de carrera de ICES'), ('JEFE_ACADEMICO', 'Jefe académico'), ('JEFE_PEDAGOGICA', 'Jefe de Pedagógica'), ('DOCENTE', 'Docente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
