# Generated by Django 5.1.15 on 2026-04-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_restore_decimal_creditos_and_recalculate'),
        ('usuarios', '0008_alter_asignacioncargo_cargo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncargo',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para Jefe de carrera y Jefe de Pedagógica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cargo', to='catalogos.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='cargo_codigo',
            field=models.CharField(choices=[('JEFE_CARRERA', 'Jefe de carrera'), ('JEFE_ACADEMICO', 'Jefe académico'), ('JEFE_PEDAGOGICA', 'Jefe de Pedagógica'), ('DOCENTE', 'Docente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
