# Generated by Django 5.1.15 on 2026-04-24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0016_restore_decimal_creditos_and_recalculate"),
        ("usuarios", "0009_asignacioncargo_carrera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadOrganizacional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clave",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_clave_format",
                                message="Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).",
                                regex="^[A-Za-z0-9_-]+$",
                            )
                        ],
                        verbose_name="Clave",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "tipo_unidad",
                    models.CharField(
                        choices=[
                            ("SECCION", "Sección"),
                            ("SUBSECCION", "Subsección"),
                            ("DEPARTAMENTO", "Departamento"),
                            ("OFICINA", "Oficina"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de unidad",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("orden", models.PositiveSmallIntegerField(default=0, verbose_name="Orden")),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo se captura cuando la unidad pertenece a una carrera.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades_organizacionales",
                        to="catalogos.carrera",
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subunidades",
                        to="usuarios.unidadorganizacional",
                        verbose_name="Unidad padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad organizacional",
                "verbose_name_plural": "Unidades organizacionales",
                "ordering": ["orden", "tipo_unidad", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="asignacioncargo",
            name="unidad_organizacional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaciones_cargo",
                to="usuarios.unidadorganizacional",
                verbose_name="Unidad organizacional",
            ),
        ),
    ]
