# Generated by Django 5.1.15 on 2026-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_unidad_organizacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='tipo_unidad',
            field=models.CharField(choices=[('SECCION', 'Sección'), ('SUBSECCION', 'Subsección')], max_length=20, verbose_name='Tipo de unidad'),
        ),
    ]
