# Generated by Django 5.1.15 on 2026-04-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_asignacioncargo_cargo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncargo',
            name='cargo_codigo',
            field=models.CharField(choices=[('JEFE_CARRERA', 'Jefe de carrera'), ('JEFE_ACADEMICO', 'Jefe académico'), ('JEFE_PEDAGOGICA', 'Jefe de Pedagógica'), ('JEFE_SUBSECCION_PEDAGOGICA', 'Jefe de subsección de Planeación y Evaluación'), ('DOCENTE', 'Docente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
