# Generated by Django 5.1.15 on 2026-04-26 00:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_asignacioncargo_cargo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_clave_format', message='Solo se permiten letras, numeros, guion medio (-) y guion bajo (_).', regex='^[A-Za-z0-9_-]+$')], verbose_name='Clave')),
                ('abreviatura', models.CharField(max_length=80, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('MILITAR_ACTIVO', 'Militar activo'), ('MILITAR_RETIRADO', 'Militar retirado'), ('CIVIL', 'Civil'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Grado/empleo',
                'verbose_name_plural': 'Grados/empleos',
                'ordering': ['tipo', 'abreviatura', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='grado_empleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.gradoempleo', verbose_name='Grado/empleo'),
        ),
    ]
