# Generated by Django 5.1.15 on 2026-05-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_gradoempleo_usuario_grado_empleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncargo',
            name='cargo_codigo',
            field=models.CharField(choices=[('JEFE_CARRERA', 'Jefe de carrera'), ('JEFE_ACADEMICO', 'Jefe académico'), ('JEFE_PEDAGOGICA', 'Jefe de Pedagógica'), ('JEFE_SUBSECCION_PEDAGOGICA', 'Jefe de subsección de Planeación y Evaluación'), ('JEFE_SUB_PLAN_EVAL', 'Jefe de subsección de Planeación y Evaluación'), ('JEFE_SUB_EJEC_CTR', 'Jefe de subsección de Ejecución y Control'), ('DOCENTE', 'Docente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
