# Generated by Django 5.1.15 on 2026-05-12 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_asignacioncargo_cargo_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncargo',
            options={'ordering': ['-activo', '-vigente_desde', 'cargo_codigo'], 'verbose_name': 'Asignación de cargo', 'verbose_name_plural': 'Asignaciones de cargo'},
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='tipo_designacion',
            field=models.CharField(choices=[('titular', 'Titular'), ('accidental', 'Accidental')], max_length=20, verbose_name='Tipo de designación'),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='vigente_desde',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Vigente desde'),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Vigente hasta'),
        ),
    ]
