# Generated by Django 5.1.15 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_asignacioncargo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=40, verbose_name='Cédula profesional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo_profesional',
            field=models.CharField(blank=True, help_text='Ejemplo: Maestro en ingeniería, Doctor en ciencias, Licenciado.', max_length=160, verbose_name='Título profesional'),
        ),
    ]
