# Generated by Django 5.1.15 on 2026-05-13 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0018_alter_periodoescolar_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoRapidoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=120, verbose_name='Etiqueta')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('icono', models.CharField(blank=True, max_length=60, verbose_name='Icono')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_rapidos_portal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso rápido de usuario',
                'verbose_name_plural': 'Accesos rápidos de usuario',
                'ordering': ['orden', 'etiqueta'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'url'), name='uq_acceso_rapido_activo_usuario_url')],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendarioInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_evento', models.CharField(choices=[('INICIO_PERIODO', 'Inicio de periodo'), ('CIERRE_CAPTURA', 'Cierre de captura'), ('PUBLICACION_ACTA', 'Publicación de acta'), ('VALIDACION_ACTA', 'Validación de acta'), ('CIERRE_PERIODO', 'Cierre de periodo'), ('APERTURA_PERIODO', 'Apertura de periodo'), ('EXTRAORDINARIO', 'Extraordinario'), ('REINGRESO', 'Reingreso'), ('EVENTO_INSTITUCIONAL', 'Evento institucional')], default='EVENTO_INSTITUCIONAL', max_length=40, verbose_name='Tipo de evento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('roles_destino', models.JSONField(blank=True, default=list, help_text='Lista opcional de roles/cargos destino. Vacío significa evento general.', verbose_name='Roles destino')),
                ('url_destino', models.CharField(blank=True, max_length=300, verbose_name='URL destino')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_calendario', to='catalogos.carrera', verbose_name='Carrera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_calendario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_calendario', to='catalogos.grupoacademico', verbose_name='Grupo académico')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_calendario', to='catalogos.periodoescolar', verbose_name='Periodo académico')),
            ],
            options={
                'verbose_name': 'Evento de calendario institucional',
                'verbose_name_plural': 'Eventos de calendario institucional',
                'ordering': ['fecha_inicio', 'titulo'],
                'indexes': [models.Index(fields=['visible', 'fecha_inicio'], name='idx_evento_visible_fecha')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('ACTA', 'Acta'), ('VALIDACION', 'Validación'), ('PERIODO', 'Periodo'), ('TRAYECTORIA', 'Trayectoria'), ('SISTEMA', 'Sistema')], default='INFO', max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_destino', models.CharField(blank=True, max_length=300, verbose_name='URL destino')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_portal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de usuario',
                'verbose_name_plural': 'Notificaciones de usuario',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-creada_en'], name='idx_notif_usuario_leida')],
            },
        ),
    ]
