from django.urls import path

from . import api_views

urlpatterns = [
    path("reportes/catalogo/", api_views.catalogo_reportes_view, name="api-reportes-catalogo"),
    path("exportaciones/", api_views.exportaciones_usuario_view, name="api-exportaciones"),
    path("exportaciones/actas-disponibles/", api_views.actas_disponibles_view, name="api-exportaciones-actas-disponibles"),
    path("exportaciones/kardex-disponibles/", api_views.kardex_disponibles_view, name="api-exportaciones-kardex-disponibles"),
    path("exportaciones/actas/<int:acta_id>/pdf/", api_views.exportar_acta_pdf_view, name="api-exportaciones-acta-pdf"),
    path("exportaciones/actas/<int:acta_id>/xlsx/", api_views.exportar_acta_xlsx_view, name="api-exportaciones-acta-xlsx"),
    path(
        "exportaciones/asignaciones/<int:asignacion_docente_id>/calificacion-final/pdf/",
        api_views.exportar_calificacion_final_pdf_view,
        name="api-exportaciones-calificacion-final-pdf",
    ),
    path(
        "exportaciones/asignaciones/<int:asignacion_docente_id>/calificacion-final/xlsx/",
        api_views.exportar_calificacion_final_xlsx_view,
        name="api-exportaciones-calificacion-final-xlsx",
    ),
    path("exportaciones/kardex/<int:discente_id>/pdf/", api_views.exportar_kardex_pdf_view, name="api-exportaciones-kardex-pdf"),
    path("reportes/operativos/actas-estado/", api_views.reporte_actas_estado_view, name="api-reportes-operativos-actas-estado"),
    path("reportes/operativos/actas-pendientes/", api_views.reporte_actas_pendientes_view, name="api-reportes-operativos-actas-pendientes"),
    path("reportes/operativos/inconformidades/", api_views.reporte_inconformidades_view, name="api-reportes-operativos-inconformidades"),
    path("reportes/operativos/sin-conformidad/", api_views.reporte_sin_conformidad_view, name="api-reportes-operativos-sin-conformidad"),
    path("reportes/operativos/actas-formalizadas/", api_views.reporte_actas_formalizadas_view, name="api-reportes-operativos-actas-formalizadas"),
    path("reportes/operativos/validaciones-acta/", api_views.reporte_validaciones_acta_view, name="api-reportes-operativos-validaciones-acta"),
    path("reportes/operativos/exportaciones-realizadas/", api_views.reporte_exportaciones_realizadas_view, name="api-reportes-operativos-exportaciones-realizadas"),
    path("exportaciones/reportes/actas-estado/xlsx/", api_views.exportar_reporte_actas_estado_xlsx_view, name="api-exportaciones-reportes-actas-estado-xlsx"),
    path("exportaciones/reportes/actas-pendientes/xlsx/", api_views.exportar_reporte_actas_pendientes_xlsx_view, name="api-exportaciones-reportes-actas-pendientes-xlsx"),
    path("exportaciones/reportes/inconformidades/xlsx/", api_views.exportar_reporte_inconformidades_xlsx_view, name="api-exportaciones-reportes-inconformidades-xlsx"),
    path("exportaciones/reportes/sin-conformidad/xlsx/", api_views.exportar_reporte_sin_conformidad_xlsx_view, name="api-exportaciones-reportes-sin-conformidad-xlsx"),
    path("exportaciones/reportes/actas-formalizadas/xlsx/", api_views.exportar_reporte_actas_formalizadas_xlsx_view, name="api-exportaciones-reportes-actas-formalizadas-xlsx"),
    path("exportaciones/reportes/validaciones-acta/xlsx/", api_views.exportar_reporte_validaciones_acta_xlsx_view, name="api-exportaciones-reportes-validaciones-acta-xlsx"),
    path("exportaciones/reportes/exportaciones-realizadas/xlsx/", api_views.exportar_reporte_exportaciones_realizadas_xlsx_view, name="api-exportaciones-reportes-exportaciones-realizadas-xlsx"),
    path("reportes/desempeno/aprobados-reprobados/", api_views.reporte_aprobados_reprobados_view, name="api-reportes-desempeno-aprobados-reprobados"),
    path("reportes/desempeno/promedios/", api_views.reporte_promedios_view, name="api-reportes-desempeno-promedios"),
    path("reportes/desempeno/distribucion/", api_views.reporte_distribucion_view, name="api-reportes-desempeno-distribucion"),
    path("reportes/desempeno/exentos/", api_views.reporte_exentos_view, name="api-reportes-desempeno-exentos"),
    path("reportes/desempeno/docentes/", api_views.reporte_desempeno_docente_view, name="api-reportes-desempeno-docentes"),
    path("reportes/desempeno/cohorte/", api_views.reporte_desempeno_cohorte_view, name="api-reportes-desempeno-cohorte"),
    path("reportes/desempeno/reprobados-nominal/", api_views.reporte_reprobados_nominal_view, name="api-reportes-desempeno-reprobados-nominal"),
    path("reportes/desempeno/cuadro-aprovechamiento/", api_views.reporte_cuadro_aprovechamiento_view, name="api-reportes-desempeno-cuadro-aprovechamiento"),
    path("exportaciones/reportes/aprobados-reprobados/xlsx/", api_views.exportar_reporte_aprobados_reprobados_xlsx_view, name="api-exportaciones-reportes-aprobados-reprobados-xlsx"),
    path("exportaciones/reportes/promedios/xlsx/", api_views.exportar_reporte_promedios_xlsx_view, name="api-exportaciones-reportes-promedios-xlsx"),
    path("exportaciones/reportes/distribucion/xlsx/", api_views.exportar_reporte_distribucion_xlsx_view, name="api-exportaciones-reportes-distribucion-xlsx"),
    path("exportaciones/reportes/exentos/xlsx/", api_views.exportar_reporte_exentos_xlsx_view, name="api-exportaciones-reportes-exentos-xlsx"),
    path("exportaciones/reportes/desempeno-docente/xlsx/", api_views.exportar_reporte_desempeno_docente_xlsx_view, name="api-exportaciones-reportes-desempeno-docente-xlsx"),
    path("exportaciones/reportes/desempeno-cohorte/xlsx/", api_views.exportar_reporte_desempeno_cohorte_xlsx_view, name="api-exportaciones-reportes-desempeno-cohorte-xlsx"),
    path("exportaciones/reportes/reprobados-nominal/xlsx/", api_views.exportar_reporte_reprobados_nominal_xlsx_view, name="api-exportaciones-reportes-reprobados-nominal-xlsx"),
    path("exportaciones/reportes/cuadro-aprovechamiento/xlsx/", api_views.exportar_reporte_cuadro_aprovechamiento_xlsx_view, name="api-exportaciones-reportes-cuadro-aprovechamiento-xlsx"),
    path("reportes/situacion/extraordinarios/", api_views.reporte_extraordinarios_view, name="api-reportes-situacion-extraordinarios"),
    path("reportes/situacion/actual/", api_views.reporte_situacion_actual_view, name="api-reportes-situacion-actual"),
    path("reportes/situacion/bajas-temporales/", api_views.reporte_bajas_temporales_view, name="api-reportes-situacion-bajas-temporales"),
    path("reportes/situacion/bajas-definitivas/", api_views.reporte_bajas_definitivas_view, name="api-reportes-situacion-bajas-definitivas"),
    path("reportes/situacion/reingresos/", api_views.reporte_reingresos_view, name="api-reportes-situacion-reingresos"),
    path("reportes/situacion/egresables/", api_views.reporte_egresables_view, name="api-reportes-situacion-egresables"),
    path("reportes/situacion/agregado/", api_views.reporte_situacion_agregado_view, name="api-reportes-situacion-agregado"),
    path("reportes/movimientos/", api_views.reporte_movimientos_academicos_view, name="api-reportes-movimientos"),
    path("reportes/movimientos/cambios-grupo/", api_views.reporte_cambios_grupo_view, name="api-reportes-movimientos-cambios-grupo"),
    path("reportes/historial-interno/", api_views.reporte_historial_interno_view, name="api-reportes-historial-interno"),
    path("reportes/historial-interno/<int:discente_id>/", api_views.reporte_historial_interno_discente_view, name="api-reportes-historial-interno-discente"),
    path("exportaciones/reportes/extraordinarios/xlsx/", api_views.exportar_reporte_extraordinarios_xlsx_view, name="api-exportaciones-reportes-extraordinarios-xlsx"),
    path("exportaciones/reportes/situacion-actual/xlsx/", api_views.exportar_reporte_situacion_actual_xlsx_view, name="api-exportaciones-reportes-situacion-actual-xlsx"),
    path("exportaciones/reportes/bajas-temporales/xlsx/", api_views.exportar_reporte_bajas_temporales_xlsx_view, name="api-exportaciones-reportes-bajas-temporales-xlsx"),
    path("exportaciones/reportes/bajas-definitivas/xlsx/", api_views.exportar_reporte_bajas_definitivas_xlsx_view, name="api-exportaciones-reportes-bajas-definitivas-xlsx"),
    path("exportaciones/reportes/reingresos/xlsx/", api_views.exportar_reporte_reingresos_xlsx_view, name="api-exportaciones-reportes-reingresos-xlsx"),
    path("exportaciones/reportes/egresables/xlsx/", api_views.exportar_reporte_egresables_xlsx_view, name="api-exportaciones-reportes-egresables-xlsx"),
    path("exportaciones/reportes/situacion-agregado/xlsx/", api_views.exportar_reporte_situacion_agregado_xlsx_view, name="api-exportaciones-reportes-situacion-agregado-xlsx"),
    path("exportaciones/reportes/movimientos-academicos/xlsx/", api_views.exportar_reporte_movimientos_academicos_xlsx_view, name="api-exportaciones-reportes-movimientos-academicos-xlsx"),
    path("exportaciones/reportes/cambios-grupo/xlsx/", api_views.exportar_reporte_cambios_grupo_xlsx_view, name="api-exportaciones-reportes-cambios-grupo-xlsx"),
    path("exportaciones/reportes/historial-interno/xlsx/", api_views.exportar_reporte_historial_interno_xlsx_view, name="api-exportaciones-reportes-historial-interno-xlsx"),
    path("exportaciones/reportes/historial-interno/<int:discente_id>/xlsx/", api_views.exportar_reporte_historial_interno_discente_xlsx_view, name="api-exportaciones-reportes-historial-interno-discente-xlsx"),
    path("exportaciones/registrar-evento-prueba/", api_views.registrar_evento_prueba_view, name="api-exportaciones-prueba"),
    path("auditoria/exportaciones/", api_views.auditoria_exportaciones_view, name="api-auditoria-exportaciones"),
]
